/* ============================================================
   Imaging Study Database & Autocomplete Engine
   ============================================================ */

const IMAGING_DB = [
// ── X-Ray ──
{name:'Chest X-Ray PA/Lateral',modality:'X-Ray',bodyRegion:'Chest',aliases:['CXR','Chest X-Ray','Chest PA/Lat'],cptCode:'71046',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:['Remove jewelry and metallic objects from chest'],contraindications:['Pregnancy (shield abdomen)'],commonIndications:['Cough','Shortness of breath','Chest pain','Pneumonia','Pre-op'],radiationDose:'Low (0.02 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Standing preferred; portable AP if unable to stand'},
{name:'Chest X-Ray AP Portable',modality:'X-Ray',bodyRegion:'Chest',aliases:['Portable CXR','AP Chest'],cptCode:'71045',contrast:'None',contrastOptions:[],estimatedDuration:'5 min',patientPrep:[],contraindications:[],commonIndications:['ICU monitoring','Post-line placement','Bedbound patient'],radiationDose:'Low (0.02 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'AP projection; note magnification artifact'},
{name:'Abdomen X-Ray (KUB)',modality:'X-Ray',bodyRegion:'Abdomen',aliases:['KUB','Flat plate abdomen','Abdominal X-Ray'],cptCode:'74018',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:['Pregnancy'],commonIndications:['Abdominal pain','Bowel obstruction','Constipation','Kidney stones'],radiationDose:'Low (0.7 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Supine; add upright if obstruction suspected'},
{name:'Acute Abdomen Series',modality:'X-Ray',bodyRegion:'Abdomen',aliases:['Obstruction Series','3-way Abdomen'],cptCode:'74022',contrast:'None',contrastOptions:[],estimatedDuration:'15 min',patientPrep:[],contraindications:[],commonIndications:['Bowel obstruction','Free air','Ileus'],radiationDose:'Low (1.0 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Includes supine, upright abdomen, and upright chest'},
{name:'Hand X-Ray',modality:'X-Ray',bodyRegion:'Hand',aliases:['X-Ray Hand'],cptCode:'73120',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:['Remove rings and jewelry'],contraindications:[],commonIndications:['Fracture','Arthritis','Foreign body','Pain/swelling'],radiationDose:'Minimal (0.001 mSv)',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'3 views: PA, lateral, oblique'},
{name:'Wrist X-Ray',modality:'X-Ray',bodyRegion:'Wrist',aliases:['X-Ray Wrist'],cptCode:'73110',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:['Remove watch/bracelet'],contraindications:[],commonIndications:['Fracture','Scaphoid injury','Pain after fall','Carpal tunnel'],radiationDose:'Minimal (0.001 mSv)',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'Include scaphoid view if scaphoid fracture suspected'},
{name:'Forearm X-Ray',modality:'X-Ray',bodyRegion:'Forearm',aliases:['X-Ray Forearm'],cptCode:'73090',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Fracture','Radius/ulna injury'],radiationDose:'Minimal',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'AP and lateral; include wrist and elbow joints'},
{name:'Elbow X-Ray',modality:'X-Ray',bodyRegion:'Elbow',aliases:['X-Ray Elbow'],cptCode:'73080',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Fracture','Dislocation','Effusion','Olecranon bursitis'],radiationDose:'Minimal',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'AP and lateral; look for fat pad sign'},
{name:'Shoulder X-Ray',modality:'X-Ray',bodyRegion:'Shoulder',aliases:['X-Ray Shoulder'],cptCode:'73030',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:['Remove shirt/bra'],contraindications:[],commonIndications:['Fracture','Dislocation','Rotator cuff calcification','Arthritis'],radiationDose:'Minimal (0.01 mSv)',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'AP internal/external rotation + axillary or Y-view'},
{name:'Humerus X-Ray',modality:'X-Ray',bodyRegion:'Humerus',aliases:['X-Ray Upper Arm'],cptCode:'73060',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Fracture','Pathologic fracture'],radiationDose:'Minimal',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'Include shoulder and elbow joints'},
{name:'Foot X-Ray',modality:'X-Ray',bodyRegion:'Foot',aliases:['X-Ray Foot'],cptCode:'73630',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Fracture','Plantar fasciitis','Gout','Diabetic foot'],radiationDose:'Minimal',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'Weight-bearing if possible; 3 views'},
{name:'Ankle X-Ray',modality:'X-Ray',bodyRegion:'Ankle',aliases:['X-Ray Ankle'],cptCode:'73610',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Fracture','Sprain','Ottawa ankle rules positive'],radiationDose:'Minimal',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'AP, lateral, mortise views'},
{name:'Tibia/Fibula X-Ray',modality:'X-Ray',bodyRegion:'Lower Leg',aliases:['X-Ray Tib/Fib','X-Ray Lower Leg'],cptCode:'73590',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Fracture','Stress fracture','Shin pain'],radiationDose:'Minimal',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'Include knee and ankle joints'},
{name:'Knee X-Ray',modality:'X-Ray',bodyRegion:'Knee',aliases:['X-Ray Knee'],cptCode:'73564',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Fracture','Osteoarthritis','Effusion','Meniscal injury'],radiationDose:'Minimal (0.005 mSv)',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'Weight-bearing AP, lateral, sunrise view; standing if arthritis eval'},
{name:'Hip X-Ray',modality:'X-Ray',bodyRegion:'Hip',aliases:['X-Ray Hip'],cptCode:'73502',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Fracture','Fall in elderly','AVN','Arthritis'],radiationDose:'Low (0.3 mSv)',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'AP and frog-leg lateral'},
{name:'Pelvis X-Ray',modality:'X-Ray',bodyRegion:'Pelvis',aliases:['X-Ray Pelvis','AP Pelvis'],cptCode:'72170',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:['Pregnancy test if female of childbearing age'],contraindications:['Pregnancy'],commonIndications:['Fracture','SI joint pain','Hip pain bilateral','Pelvic trauma'],radiationDose:'Low (0.6 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'AP supine'},
{name:'Cervical Spine X-Ray',modality:'X-Ray',bodyRegion:'Cervical Spine',aliases:['C-Spine X-Ray','X-Ray C-Spine'],cptCode:'72052',contrast:'None',contrastOptions:[],estimatedDuration:'15 min',patientPrep:['Remove necklace'],contraindications:[],commonIndications:['Neck pain','Trauma','Cervical radiculopathy','Degenerative disease'],radiationDose:'Low (0.2 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'AP, lateral, odontoid; add flexion/extension if instability suspected'},
{name:'Thoracic Spine X-Ray',modality:'X-Ray',bodyRegion:'Thoracic Spine',aliases:['T-Spine X-Ray','X-Ray T-Spine'],cptCode:'72072',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Back pain','Compression fracture','Scoliosis','Kyphosis'],radiationDose:'Low (1.0 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'AP and lateral'},
{name:'Lumbar Spine X-Ray',modality:'X-Ray',bodyRegion:'Lumbar Spine',aliases:['L-Spine X-Ray','X-Ray L-Spine','LS Spine'],cptCode:'72114',contrast:'None',contrastOptions:[],estimatedDuration:'15 min',patientPrep:['Pregnancy test if applicable'],contraindications:['Pregnancy'],commonIndications:['Low back pain','Spondylolisthesis','Compression fracture','Pre-op evaluation'],radiationDose:'Low (1.5 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'AP, lateral, obliques; flexion/extension if instability suspected'},
{name:'Rib X-Ray',modality:'X-Ray',bodyRegion:'Ribs',aliases:['X-Ray Ribs'],cptCode:'71111',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Rib fracture','Chest wall pain','Trauma'],radiationDose:'Low (0.4 mSv)',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'Include PA chest to evaluate for pneumothorax'},
{name:'Scoliosis Series',modality:'X-Ray',bodyRegion:'Full Spine',aliases:['Standing Full Spine','Scoliosis X-Ray'],cptCode:'72082',contrast:'None',contrastOptions:[],estimatedDuration:'15 min',patientPrep:[],contraindications:[],commonIndications:['Scoliosis evaluation','Scoliosis monitoring','Cobb angle measurement'],radiationDose:'Moderate (1.5 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Standing PA and lateral of entire spine on single cassette'},
{name:'Bone Age X-Ray',modality:'X-Ray',bodyRegion:'Hand',aliases:['Bone Age','Skeletal Age'],cptCode:'77072',contrast:'None',contrastOptions:[],estimatedDuration:'5 min',patientPrep:[],contraindications:[],commonIndications:['Short stature','Growth delay','Precocious puberty','Endocrine evaluation'],radiationDose:'Minimal',sedationRequired:false,laterality:'Left',lateralityOptions:[],specialInstructions:'Left hand and wrist; compare to Greulich-Pyle atlas'},
{name:'Facial Bones X-Ray',modality:'X-Ray',bodyRegion:'Face',aliases:['X-Ray Facial Bones'],cptCode:'70150',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Facial trauma','Fracture','Sinusitis'],radiationDose:'Low (0.1 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Waters, Caldwell, lateral views; CT preferred for complex fractures'},
{name:'Soft Tissue Neck X-Ray',modality:'X-Ray',bodyRegion:'Neck',aliases:['X-Ray Soft Tissue Neck','Lateral Neck'],cptCode:'70360',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Croup','Epiglottitis','Foreign body','Retropharyngeal abscess'],radiationDose:'Low (0.1 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Lateral view with neck extended; evaluate prevertebral soft tissues'},
{name:'Finger X-Ray',modality:'X-Ray',bodyRegion:'Finger',aliases:['X-Ray Finger','X-Ray Digit'],cptCode:'73140',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:['Remove rings'],contraindications:[],commonIndications:['Fracture','Dislocation','Mallet finger'],radiationDose:'Minimal',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right'],specialInstructions:'Specify which digit; PA, lateral, oblique'},
{name:'Toe X-Ray',modality:'X-Ray',bodyRegion:'Toe',aliases:['X-Ray Toe','X-Ray Great Toe'],cptCode:'73660',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Fracture','Gout','Bunion'],radiationDose:'Minimal',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right'],specialInstructions:'Specify which toe'},
{name:'Femur X-Ray',modality:'X-Ray',bodyRegion:'Femur',aliases:['X-Ray Thigh'],cptCode:'73552',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Fracture','Pathologic fracture','Bone lesion'],radiationDose:'Minimal',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'Include hip and knee joints'},

// ── CT ──
{name:'CT Head without Contrast',modality:'CT',bodyRegion:'Head',aliases:['CT Brain','Head CT','Non-con Head CT'],cptCode:'70450',contrast:'None',contrastOptions:['None','With Contrast','With and Without Contrast'],estimatedDuration:'10 min',patientPrep:['Remove metallic objects from head/neck'],contraindications:['Pregnancy (relative)'],commonIndications:['Headache','Head trauma','Stroke evaluation','Altered mental status','New neurological deficit'],radiationDose:'Moderate (2 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:''},
{name:'CT Head with Contrast',modality:'CT',bodyRegion:'Head',aliases:['CT Brain with Contrast'],cptCode:'70460',contrast:'With Contrast',contrastOptions:['With Contrast','With and Without Contrast'],estimatedDuration:'15 min',patientPrep:['Check BUN/Creatinine','NPO 4 hours','Verify no contrast allergy'],contraindications:['Contrast allergy','Severe renal insufficiency','Pregnancy'],commonIndications:['Brain tumor','Abscess','Metastases','Ring-enhancing lesion'],radiationDose:'Moderate (2 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'IV contrast required'},
{name:'CT Head with and without Contrast',modality:'CT',bodyRegion:'Head',aliases:['CT Brain w/wo'],cptCode:'70470',contrast:'With and Without',contrastOptions:[],estimatedDuration:'20 min',patientPrep:['Check BUN/Creatinine','NPO 4 hours'],contraindications:['Contrast allergy','Severe renal insufficiency'],commonIndications:['Brain tumor characterization','Infection','Pituitary mass'],radiationDose:'Moderate (4 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:''},
{name:'CTA Head',modality:'CT',bodyRegion:'Head',aliases:['CT Angiography Head','CT Angio Brain'],cptCode:'70496',contrast:'With Contrast',contrastOptions:[],estimatedDuration:'15 min',patientPrep:['Check BUN/Creatinine','IV access'],contraindications:['Contrast allergy','Renal insufficiency'],commonIndications:['Aneurysm','AVM','Vasospasm','Stroke'],radiationDose:'Moderate (2-5 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Bolus-tracked contrast injection'},
{name:'CTA Neck',modality:'CT',bodyRegion:'Neck',aliases:['CT Angiography Neck','CT Angio Carotid'],cptCode:'70498',contrast:'With Contrast',contrastOptions:[],estimatedDuration:'15 min',patientPrep:['Check BUN/Creatinine','IV access'],contraindications:['Contrast allergy','Renal insufficiency'],commonIndications:['Carotid stenosis','Stroke workup','Dissection','Vertebral stenosis'],radiationDose:'Moderate (3 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Often ordered with CTA Head'},
{name:'CT Neck with Contrast',modality:'CT',bodyRegion:'Neck',aliases:['CT Soft Tissue Neck'],cptCode:'70491',contrast:'With Contrast',contrastOptions:['With Contrast','With and Without Contrast'],estimatedDuration:'15 min',patientPrep:['Check BUN/Creatinine'],contraindications:['Contrast allergy'],commonIndications:['Neck mass','Abscess','Lymphadenopathy','Deep space infection'],radiationDose:'Moderate (3 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:''},
{name:'CT Chest without Contrast',modality:'CT',bodyRegion:'Chest',aliases:['CT Thorax','Non-con CT Chest'],cptCode:'71250',contrast:'None',contrastOptions:['None','With Contrast','With and Without Contrast'],estimatedDuration:'10 min',patientPrep:['Remove metallic objects'],contraindications:['Pregnancy'],commonIndications:['Lung nodule','Pneumonia evaluation','ILD','Pleural effusion'],radiationDose:'Moderate (7 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Breath hold required'},
{name:'CT Chest with Contrast',modality:'CT',bodyRegion:'Chest',aliases:['CT Thorax with Contrast'],cptCode:'71260',contrast:'With Contrast',contrastOptions:['With Contrast','With and Without Contrast'],estimatedDuration:'15 min',patientPrep:['Check BUN/Creatinine','NPO 4 hours'],contraindications:['Contrast allergy','Renal insufficiency'],commonIndications:['Lung mass','Mediastinal mass','Lymphadenopathy','Staging'],radiationDose:'Moderate (7 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:''},
{name:'CT Pulmonary Angiography',modality:'CT',bodyRegion:'Chest',aliases:['CTPA','PE Protocol','CT PE Study'],cptCode:'71275',contrast:'With Contrast',contrastOptions:[],estimatedDuration:'10 min',patientPrep:['Check BUN/Creatinine','IV access (18g+ preferred)'],contraindications:['Contrast allergy','Severe renal insufficiency'],commonIndications:['Pulmonary embolism','Acute dyspnea with elevated D-dimer','Chest pain with PE risk'],radiationDose:'Moderate (7 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Timed bolus to pulmonary arteries; breath hold'},
{name:'Low-Dose CT Lung Cancer Screening',modality:'CT',bodyRegion:'Chest',aliases:['LDCT','Lung Screen','Lung Cancer Screening CT'],cptCode:'71271',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:['Active symptoms warranting diagnostic CT'],commonIndications:['Lung cancer screening (USPSTF criteria)','20+ pack-year smoking history, age 50-80'],radiationDose:'Low (1.5 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Annual screening; Lung-RADS reporting'},
{name:'High-Resolution CT Chest',modality:'CT',bodyRegion:'Chest',aliases:['HRCT','HRCT Chest'],cptCode:'71250',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Interstitial lung disease','IPF','Sarcoidosis','Bronchiectasis','Hypersensitivity pneumonitis'],radiationDose:'Moderate (4 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Thin cuts (1-1.5mm); prone images may be added'},
{name:'CT Abdomen/Pelvis without Contrast',modality:'CT',bodyRegion:'Abdomen/Pelvis',aliases:['CT A/P','CT Abd/Pel Non-con'],cptCode:'74176',contrast:'None',contrastOptions:['None','With Contrast','With and Without Contrast'],estimatedDuration:'10 min',patientPrep:['NPO if possible'],contraindications:['Pregnancy'],commonIndications:['Kidney stones','Appendicitis','Diverticulitis','Abdominal pain'],radiationDose:'Moderate (10 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Non-contrast preferred for renal colic'},
{name:'CT Abdomen/Pelvis with Contrast',modality:'CT',bodyRegion:'Abdomen/Pelvis',aliases:['CT A/P with Contrast'],cptCode:'74177',contrast:'With Contrast',contrastOptions:['With Contrast','With and Without Contrast'],estimatedDuration:'15 min',patientPrep:['Check BUN/Creatinine','NPO 4 hours','Oral contrast if ordered'],contraindications:['Contrast allergy','Renal insufficiency'],commonIndications:['Abdominal pain','Abscess','Tumor staging','Appendicitis','Diverticulitis'],radiationDose:'Moderate (10 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:''},
{name:'CT Abdomen/Pelvis with and without Contrast',modality:'CT',bodyRegion:'Abdomen/Pelvis',aliases:['CT A/P w/wo'],cptCode:'74178',contrast:'With and Without',contrastOptions:[],estimatedDuration:'20 min',patientPrep:['Check BUN/Creatinine','NPO 4 hours'],contraindications:['Contrast allergy','Renal insufficiency'],commonIndications:['Liver lesion characterization','Renal mass','Pancreatic mass','Cancer staging'],radiationDose:'High (15-20 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Triple-phase for liver lesions'},
{name:'CTA Aorta',modality:'CT',bodyRegion:'Chest/Abdomen',aliases:['CT Angiography Aorta','CTA Chest/Abd/Pelvis'],cptCode:'71275',contrast:'With Contrast',contrastOptions:[],estimatedDuration:'15 min',patientPrep:['Check BUN/Creatinine','Large bore IV'],contraindications:['Contrast allergy','Renal insufficiency'],commonIndications:['Aortic dissection','Aortic aneurysm','Post-surgical follow-up','Trauma'],radiationDose:'Moderate (10 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'ECG-gated if thoracic aorta'},
{name:'CTA Coronary',modality:'CT',bodyRegion:'Heart',aliases:['Coronary CTA','CT Coronary Angiography','CCTA'],cptCode:'75574',contrast:'With Contrast',contrastOptions:[],estimatedDuration:'20 min',patientPrep:['Check BUN/Creatinine','HR <65 (beta-blocker if needed)','NPO 4 hours','No caffeine 12 hours','Sublingual nitro before scan'],contraindications:['Contrast allergy','Irregular heart rhythm','HR >65 despite beta-blocker'],commonIndications:['Chest pain risk stratification','CAD evaluation','Coronary anomaly'],radiationDose:'Moderate (5-10 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'ECG-gated; HR control critical'},
{name:'CT Calcium Score',modality:'CT',bodyRegion:'Heart',aliases:['Coronary Calcium Score','Agatston Score'],cptCode:'75571',contrast:'None',contrastOptions:[],estimatedDuration:'10 min',patientPrep:['No caffeine 12 hours'],contraindications:[],commonIndications:['Cardiovascular risk assessment','Intermediate risk patients'],radiationDose:'Low (1 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Non-contrast; ECG-gated'},
{name:'CT Sinuses',modality:'CT',bodyRegion:'Sinuses',aliases:['Sinus CT','CT Paranasal Sinuses'],cptCode:'70486',contrast:'None',contrastOptions:['None','With Contrast'],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Chronic sinusitis','Pre-FESS','Nasal polyps','Facial pain'],radiationDose:'Low (0.6 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Coronal and axial reformats'},
{name:'CT Cervical Spine without Contrast',modality:'CT',bodyRegion:'Cervical Spine',aliases:['CT C-Spine'],cptCode:'72125',contrast:'None',contrastOptions:['None','With Contrast'],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Trauma','Fracture evaluation','Cervical stenosis'],radiationDose:'Moderate (3 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:''},
{name:'CT Lumbar Spine without Contrast',modality:'CT',bodyRegion:'Lumbar Spine',aliases:['CT L-Spine'],cptCode:'72131',contrast:'None',contrastOptions:['None','With Contrast'],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Fracture','Stenosis','Post-surgical evaluation','MRI contraindicated'],radiationDose:'Moderate (6 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:''},
{name:'CT Enterography',modality:'CT',bodyRegion:'Abdomen',aliases:['CTE','CT Enterography'],cptCode:'74178',contrast:'With Contrast',contrastOptions:[],estimatedDuration:'30 min',patientPrep:['Drink 1350 mL oral contrast over 1 hour before scan','NPO 4 hours before prep','Check BUN/Creatinine'],contraindications:['Contrast allergy','Bowel obstruction'],commonIndications:['Crohn disease','Small bowel evaluation','Obscure GI bleeding','Small bowel tumor'],radiationDose:'Moderate (10 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Enteric contrast distends small bowel for evaluation'},
{name:'CT Temporal Bones',modality:'CT',bodyRegion:'Temporal Bones',aliases:['CT Petrous Bones','CT IAC'],cptCode:'70480',contrast:'None',contrastOptions:['None','With Contrast'],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Hearing loss','Cholesteatoma','Temporal bone fracture','Cochlear implant planning','Mastoiditis'],radiationDose:'Moderate (2 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'High-resolution thin cuts'},
{name:'CT Orbits',modality:'CT',bodyRegion:'Orbits',aliases:['CT Eyes'],cptCode:'70480',contrast:'None',contrastOptions:['None','With Contrast','With and Without Contrast'],estimatedDuration:'10 min',patientPrep:[],contraindications:[],commonIndications:['Orbital fracture','Proptosis','Orbital cellulitis','Foreign body'],radiationDose:'Moderate (2 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Thin cuts; axial and coronal reformats'},

// ── MRI ──
{name:'MRI Brain without Contrast',modality:'MRI',bodyRegion:'Brain',aliases:['MRI Head','MRI Brain'],cptCode:'70551',contrast:'None',contrastOptions:['None','With Contrast','With and Without Contrast'],estimatedDuration:'30 min',patientPrep:['MRI safety screening','Remove all metallic objects'],contraindications:['Pacemaker (non-MRI-conditional)','Metallic implants','Cochlear implant (non-compatible)','Severe claustrophobia'],commonIndications:['Headache','Seizure','Stroke','Dementia workup','MS evaluation'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Screen for metallic implants'},
{name:'MRI Brain with and without Contrast',modality:'MRI',bodyRegion:'Brain',aliases:['MRI Brain w/wo'],cptCode:'70553',contrast:'With and Without',contrastOptions:[],estimatedDuration:'45 min',patientPrep:['MRI safety screening','Check eGFR for gadolinium','Remove metallic objects'],contraindications:['Pacemaker','Metallic implants','eGFR <30 (gadolinium risk)','Gadolinium allergy'],commonIndications:['Brain tumor','Metastases','Infection/abscess','MS','Pituitary mass'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'IV gadolinium contrast'},
{name:'MRA Brain',modality:'MRI',bodyRegion:'Brain',aliases:['MR Angiography Brain','MRA Head','MRA Circle of Willis'],cptCode:'70544',contrast:'None',contrastOptions:['None','With Contrast'],estimatedDuration:'30 min',patientPrep:['MRI safety screening'],contraindications:['Pacemaker','Metallic implants'],commonIndications:['Aneurysm screening','Stroke','AVM','Vasculitis','Moyamoya'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Time-of-flight technique; no contrast usually needed'},
{name:'MRA Neck',modality:'MRI',bodyRegion:'Neck',aliases:['MR Angiography Neck','MRA Carotid'],cptCode:'70547',contrast:'With Contrast',contrastOptions:['None','With Contrast'],estimatedDuration:'30 min',patientPrep:['MRI safety screening','Check eGFR'],contraindications:['Pacemaker','Metallic implants','eGFR <30'],commonIndications:['Carotid stenosis','Vertebral dissection','Stroke workup'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:''},
{name:'MRI Cervical Spine without Contrast',modality:'MRI',bodyRegion:'Cervical Spine',aliases:['MRI C-Spine'],cptCode:'72141',contrast:'None',contrastOptions:['None','With Contrast','With and Without Contrast'],estimatedDuration:'30 min',patientPrep:['MRI safety screening'],contraindications:['Pacemaker','Metallic implants','Claustrophobia'],commonIndications:['Radiculopathy','Myelopathy','Disc herniation','Stenosis','Cord compression'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:''},
{name:'MRI Thoracic Spine without Contrast',modality:'MRI',bodyRegion:'Thoracic Spine',aliases:['MRI T-Spine'],cptCode:'72146',contrast:'None',contrastOptions:['None','With Contrast','With and Without Contrast'],estimatedDuration:'30 min',patientPrep:['MRI safety screening'],contraindications:['Pacemaker','Metallic implants'],commonIndications:['Myelopathy','Compression fracture','Cord compression','Thoracic disc herniation'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:''},
{name:'MRI Lumbar Spine without Contrast',modality:'MRI',bodyRegion:'Lumbar Spine',aliases:['MRI L-Spine','MRI Lower Back'],cptCode:'72148',contrast:'None',contrastOptions:['None','With Contrast','With and Without Contrast'],estimatedDuration:'30 min',patientPrep:['MRI safety screening'],contraindications:['Pacemaker','Metallic implants','Claustrophobia'],commonIndications:['Low back pain with red flags','Radiculopathy','Disc herniation','Stenosis','Cauda equina syndrome'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:''},
{name:'MRI Abdomen',modality:'MRI',bodyRegion:'Abdomen',aliases:['MRI Abdomen'],cptCode:'74181',contrast:'None',contrastOptions:['None','With Contrast','With and Without Contrast'],estimatedDuration:'45 min',patientPrep:['MRI safety screening','NPO 4 hours'],contraindications:['Pacemaker','Metallic implants'],commonIndications:['Liver lesion','Adrenal mass','Renal mass characterization'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:''},
{name:'MRCP',modality:'MRI',bodyRegion:'Abdomen',aliases:['MR Cholangiopancreatography'],cptCode:'74181',contrast:'None',contrastOptions:[],estimatedDuration:'45 min',patientPrep:['NPO 4 hours','MRI safety screening'],contraindications:['Pacemaker','Metallic implants'],commonIndications:['Bile duct stones','Cholangitis','Pancreatic duct evaluation','Biliary obstruction','PSC'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Non-contrast; heavily T2-weighted sequences'},
{name:'MRI Pelvis',modality:'MRI',bodyRegion:'Pelvis',aliases:['MRI Pelvis'],cptCode:'72195',contrast:'None',contrastOptions:['None','With Contrast','With and Without Contrast'],estimatedDuration:'45 min',patientPrep:['MRI safety screening'],contraindications:['Pacemaker','Metallic implants'],commonIndications:['Rectal cancer staging','Cervical cancer staging','Perianal fistula','Endometriosis'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:''},
{name:'MRI Prostate (Multiparametric)',modality:'MRI',bodyRegion:'Prostate',aliases:['mpMRI Prostate','PI-RADS MRI'],cptCode:'72197',contrast:'With and Without',contrastOptions:[],estimatedDuration:'45-60 min',patientPrep:['MRI safety screening','Fleet enema 1 hour before','No ejaculation 3 days prior','Check eGFR'],contraindications:['Pacemaker','Hip prosthesis (relative)','eGFR <30'],commonIndications:['Elevated PSA','Active surveillance','Pre-biopsy evaluation','PI-RADS scoring'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Endorectal coil may be used; PI-RADS v2.1 reporting'},
{name:'Cardiac MRI',modality:'MRI',bodyRegion:'Heart',aliases:['CMR','Cardiac MR','MRI Heart'],cptCode:'75557',contrast:'None',contrastOptions:['None','With Contrast'],estimatedDuration:'60 min',patientPrep:['MRI safety screening','ECG gating required'],contraindications:['Pacemaker','ICD','Severe arrhythmia'],commonIndications:['Cardiomyopathy','Myocarditis','Cardiac mass','Viability assessment','Iron overload','ARVC'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'ECG-gated; breath holds required; adenosine stress if ordered'},
{name:'MRI Shoulder',modality:'MRI',bodyRegion:'Shoulder',aliases:['MRI Shoulder'],cptCode:'73221',contrast:'None',contrastOptions:['None','With Contrast','With and Without Contrast'],estimatedDuration:'30-45 min',patientPrep:['MRI safety screening','Remove metallic objects'],contraindications:['Pacemaker','Metallic implants'],commonIndications:['Rotator cuff tear','Labral tear','Impingement','Shoulder instability'],radiationDose:'None',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right'],specialInstructions:'Arthrogram may improve labral visualization'},
{name:'MRI Knee',modality:'MRI',bodyRegion:'Knee',aliases:['MRI Knee'],cptCode:'73721',contrast:'None',contrastOptions:['None','With Contrast'],estimatedDuration:'30-45 min',patientPrep:['MRI safety screening'],contraindications:['Pacemaker','Metallic implants in knee'],commonIndications:['Meniscal tear','ACL/PCL tear','Cartilage injury','Bone bruise','Baker cyst'],radiationDose:'None',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right'],specialInstructions:''},
{name:'MRI Hip',modality:'MRI',bodyRegion:'Hip',aliases:['MRI Hip'],cptCode:'73721',contrast:'None',contrastOptions:['None','With Contrast'],estimatedDuration:'30-45 min',patientPrep:['MRI safety screening'],contraindications:['Pacemaker','Hip prosthesis (may cause artifact)'],commonIndications:['AVN','Labral tear','Stress fracture','Occult fracture','Hamstring tear'],radiationDose:'None',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:''},
{name:'MRI Ankle',modality:'MRI',bodyRegion:'Ankle',aliases:['MRI Ankle','MRI Foot/Ankle'],cptCode:'73721',contrast:'None',contrastOptions:['None','With Contrast'],estimatedDuration:'30-45 min',patientPrep:['MRI safety screening'],contraindications:['Pacemaker','Metallic implants'],commonIndications:['Achilles tendon tear','Ligament injury','Stress fracture','Osteochondral defect','Tarsal coalition'],radiationDose:'None',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right'],specialInstructions:''},
{name:'MRI Wrist',modality:'MRI',bodyRegion:'Wrist',aliases:['MRI Wrist'],cptCode:'73221',contrast:'None',contrastOptions:['None','With Contrast'],estimatedDuration:'30-45 min',patientPrep:['MRI safety screening','Remove jewelry'],contraindications:['Pacemaker','Metallic implants'],commonIndications:['Scaphoid fracture','TFCC tear','Carpal tunnel','Ganglion cyst','AVN scaphoid/lunate'],radiationDose:'None',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right'],specialInstructions:''},
{name:'MRI Elbow',modality:'MRI',bodyRegion:'Elbow',aliases:['MRI Elbow'],cptCode:'73221',contrast:'None',contrastOptions:['None','With Contrast'],estimatedDuration:'30-45 min',patientPrep:['MRI safety screening'],contraindications:['Pacemaker','Metallic implants'],commonIndications:['Lateral epicondylitis','UCL tear','Loose body','Biceps tendon tear'],radiationDose:'None',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right'],specialInstructions:''},
{name:'Breast MRI',modality:'MRI',bodyRegion:'Breast',aliases:['MRI Breast','Breast MR'],cptCode:'77049',contrast:'With and Without Contrast',contrastOptions:[],estimatedDuration:'45-60 min',patientPrep:['MRI safety screening','Check eGFR','Schedule day 7-14 of menstrual cycle if premenopausal'],contraindications:['Pacemaker','eGFR <30','Gadolinium allergy'],commonIndications:['High-risk breast cancer screening','Extent of disease','Implant evaluation','Occult primary','Neo-adjuvant therapy monitoring'],radiationDose:'None',sedationRequired:false,laterality:'Bilateral',lateralityOptions:['Bilateral'],specialInstructions:'Prone positioning; gadolinium required; BI-RADS reporting'},
{name:'MRI Enterography',modality:'MRI',bodyRegion:'Abdomen',aliases:['MRE','MR Enterography'],cptCode:'74183',contrast:'With Contrast',contrastOptions:[],estimatedDuration:'60 min',patientPrep:['Drink oral contrast 45 min before','NPO 4 hours','MRI safety screening','Check eGFR'],contraindications:['Pacemaker','Bowel obstruction','eGFR <30'],commonIndications:['Crohn disease','Small bowel evaluation','Pediatric IBD (radiation-free)'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Preferred over CTE in young patients (no radiation)'},
{name:'MRI Arthrogram Shoulder',modality:'MRI',bodyRegion:'Shoulder',aliases:['MRA Shoulder','Shoulder Arthrogram'],cptCode:'73222',contrast:'Intra-articular + IV',contrastOptions:[],estimatedDuration:'60 min',patientPrep:['MRI safety screening','Fluoroscopy-guided injection first'],contraindications:['Joint infection','Pacemaker','Gadolinium allergy'],commonIndications:['Labral tear','SLAP lesion','Rotator cuff partial tear','Capsular pathology'],radiationDose:'None (MRI) + Minimal (fluoro)',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right'],specialInstructions:'Intra-articular gadolinium injected under fluoroscopy, then MRI'},

// ── Ultrasound ──
{name:'Ultrasound Abdomen Complete',modality:'Ultrasound',bodyRegion:'Abdomen',aliases:['US Abdomen','Abdominal Ultrasound'],cptCode:'76700',contrast:'None',contrastOptions:[],estimatedDuration:'30 min',patientPrep:['NPO 8 hours'],contraindications:[],commonIndications:['RUQ pain','Gallstones','Liver disease','Ascites','AAA screening'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Fasting improves gallbladder visualization'},
{name:'Ultrasound RUQ',modality:'Ultrasound',bodyRegion:'Right Upper Quadrant',aliases:['US RUQ','RUQ Ultrasound','Gallbladder Ultrasound'],cptCode:'76705',contrast:'None',contrastOptions:[],estimatedDuration:'20 min',patientPrep:['NPO 8 hours'],contraindications:[],commonIndications:['Gallstones','Cholecystitis','RUQ pain','Biliary dilation'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Fasting required for gallbladder distension'},
{name:'Ultrasound Renal/Bladder',modality:'Ultrasound',bodyRegion:'Kidneys',aliases:['US Renal','Kidney Ultrasound','Renal US'],cptCode:'76770',contrast:'None',contrastOptions:[],estimatedDuration:'30 min',patientPrep:['Full bladder preferred'],contraindications:[],commonIndications:['Hydronephrosis','Kidney stones','Renal mass','AKI','CKD monitoring','Hematuria'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Full bladder for post-void residual measurement'},
{name:'Ultrasound Pelvis (Transabdominal)',modality:'Ultrasound',bodyRegion:'Pelvis',aliases:['US Pelvis','Pelvic Ultrasound','Pelvic US'],cptCode:'76856',contrast:'None',contrastOptions:[],estimatedDuration:'20 min',patientPrep:['Full bladder'],contraindications:[],commonIndications:['Pelvic mass','Uterine fibroids','Ovarian cyst','Pelvic pain'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Full bladder required as acoustic window'},
{name:'Ultrasound Pelvis (Transvaginal)',modality:'Ultrasound',bodyRegion:'Pelvis',aliases:['TVUS','Transvaginal Ultrasound','Endovaginal US'],cptCode:'76830',contrast:'None',contrastOptions:[],estimatedDuration:'20 min',patientPrep:['Empty bladder'],contraindications:['Patient refusal','Vaginal stenosis'],commonIndications:['Abnormal uterine bleeding','Endometrial evaluation','Ovarian cyst','Ectopic pregnancy','Infertility'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Empty bladder; endovaginal probe'},
{name:'OB Ultrasound (1st Trimester)',modality:'Ultrasound',bodyRegion:'Pelvis',aliases:['Dating Ultrasound','1st Trimester US','Early OB US'],cptCode:'76801',contrast:'None',contrastOptions:[],estimatedDuration:'20 min',patientPrep:['Full bladder for transabdominal'],contraindications:[],commonIndications:['Pregnancy dating','Viability','Ectopic pregnancy','Threatened abortion'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'May require transvaginal approach'},
{name:'OB Ultrasound (Anatomy Scan)',modality:'Ultrasound',bodyRegion:'Pelvis',aliases:['Anatomy Scan','Level 2 US','20-Week Ultrasound','Fetal Survey'],cptCode:'76811',contrast:'None',contrastOptions:[],estimatedDuration:'45 min',patientPrep:[],contraindications:[],commonIndications:['Fetal anatomy survey','18-22 week screening','Structural anomaly evaluation'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Detailed fetal anatomy evaluation'},
{name:'Biophysical Profile',modality:'Ultrasound',bodyRegion:'Pelvis',aliases:['BPP','Fetal BPP'],cptCode:'76818',contrast:'None',contrastOptions:[],estimatedDuration:'30 min',patientPrep:[],contraindications:[],commonIndications:['High-risk pregnancy','Post-dates','Decreased fetal movement','Growth restriction'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Evaluates breathing, movement, tone, amniotic fluid; may include NST'},
{name:'Nuchal Translucency Ultrasound',modality:'Ultrasound',bodyRegion:'Pelvis',aliases:['NT Scan','Nuchal Translucency','1st Trimester Screen US'],cptCode:'76813',contrast:'None',contrastOptions:[],estimatedDuration:'30 min',patientPrep:[],contraindications:[],commonIndications:['Down syndrome screening','Trisomy screening','11-14 weeks gestation'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Must be performed at 11w0d to 13w6d; combine with serum markers'},
{name:'Thyroid Ultrasound',modality:'Ultrasound',bodyRegion:'Thyroid',aliases:['US Thyroid','Thyroid US'],cptCode:'76536',contrast:'None',contrastOptions:[],estimatedDuration:'20 min',patientPrep:['Remove necklace'],contraindications:[],commonIndications:['Thyroid nodule','Goiter','Thyroid cancer surveillance','Abnormal thyroid function'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'TI-RADS reporting for nodules'},
{name:'Breast Ultrasound',modality:'Ultrasound',bodyRegion:'Breast',aliases:['US Breast','Breast US'],cptCode:'76641',contrast:'None',contrastOptions:[],estimatedDuration:'20 min',patientPrep:[],contraindications:[],commonIndications:['Palpable mass','Mammographic abnormality','Dense breasts','Breast pain'],radiationDose:'None',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'BI-RADS reporting'},
{name:'Scrotal Ultrasound',modality:'Ultrasound',bodyRegion:'Scrotum',aliases:['US Scrotum','Testicular Ultrasound','US Testes'],cptCode:'76870',contrast:'None',contrastOptions:[],estimatedDuration:'20 min',patientPrep:[],contraindications:[],commonIndications:['Testicular mass','Testicular pain','Epididymitis','Hydrocele','Varicocele','Testicular torsion'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Color Doppler for torsion evaluation; STAT for acute pain'},
{name:'Carotid Duplex Ultrasound',modality:'Ultrasound',bodyRegion:'Neck',aliases:['Carotid US','Carotid Doppler','Carotid Duplex'],cptCode:'93880',contrast:'None',contrastOptions:[],estimatedDuration:'30 min',patientPrep:['Remove necklace'],contraindications:[],commonIndications:['Carotid stenosis screening','Stroke/TIA','Carotid bruit','Pre-CABG'],radiationDose:'None',sedationRequired:false,laterality:'Bilateral',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:''},
{name:'Lower Extremity Venous Duplex',modality:'Ultrasound',bodyRegion:'Lower Extremity',aliases:['DVT Study','LE Venous Doppler','Leg Duplex'],cptCode:'93970',contrast:'None',contrastOptions:[],estimatedDuration:'30 min',patientPrep:[],contraindications:[],commonIndications:['DVT','Leg swelling','Leg pain','Pre-op DVT screening','Elevated D-dimer'],radiationDose:'None',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'Compression and Doppler technique'},
{name:'Upper Extremity Venous Duplex',modality:'Ultrasound',bodyRegion:'Upper Extremity',aliases:['UE Venous Doppler','Arm DVT Study'],cptCode:'93971',contrast:'None',contrastOptions:[],estimatedDuration:'30 min',patientPrep:[],contraindications:[],commonIndications:['Upper extremity DVT','Arm swelling','PICC-associated DVT','SVC syndrome'],radiationDose:'None',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:''},
{name:'Lower Extremity Arterial Duplex',modality:'Ultrasound',bodyRegion:'Lower Extremity',aliases:['LE Arterial Doppler','ABI Study'],cptCode:'93925',contrast:'None',contrastOptions:[],estimatedDuration:'45 min',patientPrep:[],contraindications:[],commonIndications:['PAD','Claudication','Non-healing wound','Pre-amputation evaluation'],radiationDose:'None',sedationRequired:false,laterality:'Bilateral',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'Includes ankle-brachial index'},
{name:'Renal Artery Duplex',modality:'Ultrasound',bodyRegion:'Kidneys',aliases:['Renal Artery Doppler','Renal Duplex'],cptCode:'93976',contrast:'None',contrastOptions:[],estimatedDuration:'45 min',patientPrep:['NPO 8 hours'],contraindications:[],commonIndications:['Renal artery stenosis','Resistant hypertension','Renal transplant evaluation'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Fasting improves visualization'},
{name:'Echocardiogram (TTE)',modality:'Ultrasound',bodyRegion:'Heart',aliases:['Echo','TTE','Transthoracic Echo','Cardiac Echo'],cptCode:'93306',contrast:'None',contrastOptions:[],estimatedDuration:'45 min',patientPrep:[],contraindications:[],commonIndications:['Heart failure','Valvular disease','Murmur','Dyspnea','Cardiomyopathy','Pericardial effusion'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Left lateral decubitus position'},
{name:'Transesophageal Echocardiogram',modality:'Ultrasound',bodyRegion:'Heart',aliases:['TEE','Transesophageal Echo'],cptCode:'93312',contrast:'None',contrastOptions:[],estimatedDuration:'45-60 min',patientPrep:['NPO 6 hours','IV access','Consent required'],contraindications:['Esophageal stricture','Esophageal varices','Recent esophageal surgery'],commonIndications:['Endocarditis','Atrial appendage thrombus','Valvular disease detail','Aortic dissection','Intraoperative'],radiationDose:'None',sedationRequired:true,laterality:'N/A',lateralityOptions:[],specialInstructions:'Requires sedation; esophageal probe insertion'},
{name:'Stress Echocardiogram',modality:'Ultrasound',bodyRegion:'Heart',aliases:['Stress Echo','Exercise Echo','Dobutamine Echo'],cptCode:'93351',contrast:'None',contrastOptions:[],estimatedDuration:'60 min',patientPrep:['NPO 4 hours','Wear comfortable clothes/shoes','Hold beta-blockers 24-48h if stress test'],contraindications:['Unstable angina','Aortic stenosis (severe)','Decompensated heart failure'],commonIndications:['Chest pain evaluation','CAD evaluation','Pre-op cardiac risk','Valvular assessment with exercise'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Exercise treadmill or pharmacologic (dobutamine) stress'},
{name:'FAST Exam',modality:'Ultrasound',bodyRegion:'Abdomen',aliases:['FAST','Focused Assessment with Sonography for Trauma'],cptCode:'76705',contrast:'None',contrastOptions:[],estimatedDuration:'5 min',patientPrep:[],contraindications:[],commonIndications:['Trauma','Hemodynamic instability','Blunt abdominal trauma'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Point-of-care; 4 views: RUQ, LUQ, pelvis, subxiphoid'},
{name:'Soft Tissue Ultrasound',modality:'Ultrasound',bodyRegion:'Soft Tissue',aliases:['US Soft Tissue','Superficial US'],cptCode:'76536',contrast:'None',contrastOptions:[],estimatedDuration:'20 min',patientPrep:[],contraindications:[],commonIndications:['Palpable mass','Abscess','Lipoma','Foreign body','Lymph node evaluation'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Mark area of concern'},
{name:'Appendix Ultrasound',modality:'Ultrasound',bodyRegion:'Abdomen',aliases:['US Appendix','Pediatric Appendix US'],cptCode:'76705',contrast:'None',contrastOptions:[],estimatedDuration:'20 min',patientPrep:[],contraindications:[],commonIndications:['Appendicitis (pediatric)','RLQ pain'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'First-line imaging for appendicitis in children; graded compression technique'},

// ── Nuclear Medicine ──
{name:'Bone Scan (Whole Body)',modality:'Nuclear Medicine',bodyRegion:'Whole Body',aliases:['Bone Scintigraphy','Tc-99m Bone Scan','Skeletal Survey NM'],cptCode:'78300',contrast:'None',contrastOptions:[],estimatedDuration:'3-4 hours',patientPrep:['Hydrate well','Void before scan'],contraindications:['Pregnancy','Breastfeeding'],commonIndications:['Bone metastases','Occult fracture','Osteomyelitis','Paget disease','Prosthetic loosening'],radiationDose:'Moderate (6 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'IV Tc-99m MDP injection; 2-3 hour delay before scanning'},
{name:'Three-Phase Bone Scan',modality:'Nuclear Medicine',bodyRegion:'Targeted',aliases:['3-Phase Bone Scan'],cptCode:'78315',contrast:'None',contrastOptions:[],estimatedDuration:'4 hours',patientPrep:['Hydrate well'],contraindications:['Pregnancy'],commonIndications:['Osteomyelitis','Complex regional pain syndrome','Prosthetic infection','Stress fracture'],radiationDose:'Moderate (6 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Flow, blood pool, and delayed phases'},
{name:'VQ Scan',modality:'Nuclear Medicine',bodyRegion:'Chest',aliases:['V/Q Scan','Ventilation-Perfusion Scan','Lung Scan'],cptCode:'78582',contrast:'None',contrastOptions:[],estimatedDuration:'60 min',patientPrep:[],contraindications:['Severe pulmonary HTN (relative)'],commonIndications:['Pulmonary embolism (contrast allergy or renal failure)','Pregnancy with PE concern','Pre-op lung function assessment'],radiationDose:'Low (2 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Ventilation with Xe-133 or Tc-99m DTPA aerosol; perfusion with Tc-99m MAA'},
{name:'Thyroid Uptake and Scan',modality:'Nuclear Medicine',bodyRegion:'Thyroid',aliases:['RAIU','Thyroid Scan','I-123 Thyroid'],cptCode:'78014',contrast:'None',contrastOptions:[],estimatedDuration:'2 visits (4h + 24h)',patientPrep:['Stop thyroid medications per ordering provider','No iodinated contrast in prior 6-8 weeks','Low-iodine diet 1-2 weeks before'],contraindications:['Pregnancy','Breastfeeding','Recent iodinated contrast'],commonIndications:['Hyperthyroidism (Graves vs toxic nodule)','Thyroid nodule evaluation'],radiationDose:'Low (1 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'I-123 capsule; uptake at 4 and 24 hours; scan at 24 hours'},
{name:'Parathyroid Sestamibi Scan',modality:'Nuclear Medicine',bodyRegion:'Neck/Chest',aliases:['Parathyroid Scan','Sestamibi Scan'],cptCode:'78072',contrast:'None',contrastOptions:[],estimatedDuration:'3-4 hours',patientPrep:[],contraindications:['Pregnancy'],commonIndications:['Primary hyperparathyroidism','Parathyroid adenoma localization','Pre-surgical planning'],radiationDose:'Moderate (8 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Tc-99m sestamibi with SPECT; dual-phase or subtraction technique'},
{name:'HIDA Scan',modality:'Nuclear Medicine',bodyRegion:'Abdomen',aliases:['Hepatobiliary Scan','DISIDA','Cholescintigraphy'],cptCode:'78226',contrast:'None',contrastOptions:[],estimatedDuration:'1-4 hours',patientPrep:['NPO 2-4 hours (but not >24 hours)'],contraindications:['Pregnancy'],commonIndications:['Acute cholecystitis','Biliary dyskinesia','Bile leak','Biliary atresia'],radiationDose:'Moderate (3 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Add CCK stimulation for gallbladder ejection fraction (GBEF); morphine augmentation if non-filling at 1 hour'},
{name:'Gastric Emptying Study',modality:'Nuclear Medicine',bodyRegion:'Abdomen',aliases:['GES','Gastric Motility Study'],cptCode:'78264',contrast:'None',contrastOptions:[],estimatedDuration:'4 hours',patientPrep:['NPO overnight','Hold prokinetics 48 hours','Hold opioids 48 hours'],contraindications:['Egg allergy (egg-based meal)','Pregnancy'],commonIndications:['Gastroparesis','Nausea/vomiting','Diabetes with GI symptoms','Post-surgical dysmotility'],radiationDose:'Low (1 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Standardized Tc-99m egg meal; images at 0, 1, 2, 4 hours'},
{name:'GI Bleeding Scan',modality:'Nuclear Medicine',bodyRegion:'Abdomen',aliases:['Tagged RBC Scan','Tc-99m RBC Scan','Bleeding Scan'],cptCode:'78278',contrast:'None',contrastOptions:[],estimatedDuration:'1-24 hours',patientPrep:['Active bleeding required'],contraindications:['Pregnancy'],commonIndications:['Active GI bleeding','Lower GI bleed localization','Intermittent GI bleeding'],radiationDose:'Moderate (7 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Tc-99m labeled RBCs; continuous imaging during active bleed; can detect 0.1-0.4 mL/min bleeding'},
{name:'Myocardial Perfusion Imaging',modality:'Nuclear Medicine',bodyRegion:'Heart',aliases:['Nuclear Stress Test','MPI','Stress/Rest Myocardial Perfusion','Sestamibi Stress'],cptCode:'78452',contrast:'None',contrastOptions:[],estimatedDuration:'3-4 hours',patientPrep:['NPO 4 hours','No caffeine 24 hours','Wear comfortable shoes','Hold beta-blockers if exercise','Hold dipyridamole/theophylline if pharmacologic'],contraindications:['Unstable angina','Recent MI (<48h)','Severe aortic stenosis'],commonIndications:['Chest pain','CAD evaluation','Pre-op cardiac risk','Known CAD — ischemia assessment'],radiationDose:'Moderate (10-12 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Exercise or pharmacologic (regadenoson/adenosine) stress; rest and stress SPECT images'},
{name:'MUGA Scan',modality:'Nuclear Medicine',bodyRegion:'Heart',aliases:['Radionuclide Ventriculography','Gated Blood Pool Scan','RVG'],cptCode:'78473',contrast:'None',contrastOptions:[],estimatedDuration:'60 min',patientPrep:[],contraindications:['Pregnancy'],commonIndications:['LVEF measurement','Chemotherapy monitoring (doxorubicin)','Heart failure'],radiationDose:'Moderate (8 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'ECG-gated; Tc-99m labeled RBCs'},
{name:'Renal Scan (MAG3)',modality:'Nuclear Medicine',bodyRegion:'Kidneys',aliases:['MAG3 Renal Scan','Lasix Renogram','Diuretic Renogram'],cptCode:'78708',contrast:'None',contrastOptions:[],estimatedDuration:'60 min',patientPrep:['Hydrate well','IV access'],contraindications:['Pregnancy'],commonIndications:['Renal obstruction','Hydronephrosis','Renal function assessment','Transplant evaluation'],radiationDose:'Low (1 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Tc-99m MAG3 injection; Lasix given at 20 min if obstruction suspected'},

// ── PET/CT ──
{name:'PET/CT FDG Whole Body',modality:'PET/CT',bodyRegion:'Whole Body',aliases:['PET Scan','PET/CT','FDG PET','Oncologic PET'],cptCode:'78816',contrast:'None',contrastOptions:[],estimatedDuration:'90 min',patientPrep:['NPO 6 hours','Blood glucose <200','No strenuous exercise 24 hours','Hydrate well'],contraindications:['Pregnancy','Uncontrolled diabetes'],commonIndications:['Cancer staging','Treatment response','Lymphoma','Lung cancer','Unknown primary','Recurrence evaluation'],radiationDose:'Moderate (14 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'F-18 FDG injection; 60 min uptake period; patient rests quietly'},
{name:'PET/CT Brain (FDG)',modality:'PET/CT',bodyRegion:'Brain',aliases:['Brain PET','FDG Brain PET'],cptCode:'78608',contrast:'None',contrastOptions:[],estimatedDuration:'60 min',patientPrep:['NPO 4 hours','Quiet room during uptake','No reading/talking during uptake'],contraindications:['Pregnancy'],commonIndications:['Dementia evaluation','Epilepsy focus localization','Brain tumor recurrence vs radiation necrosis'],radiationDose:'Low (5 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'30 min quiet uptake in dark room'},
{name:'PET/CT Brain (Amyloid)',modality:'PET/CT',bodyRegion:'Brain',aliases:['Amyloid PET','Amyvid PET','Florbetapir PET'],cptCode:'78811',contrast:'None',contrastOptions:[],estimatedDuration:'60 min',patientPrep:[],contraindications:['Pregnancy'],commonIndications:['Alzheimer disease evaluation','Amyloid plaque detection','Dementia workup'],radiationDose:'Low (7 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'F-18 florbetapir (Amyvid); 50 min uptake'},
{name:'PET/CT Ga-68 DOTATATE',modality:'PET/CT',bodyRegion:'Whole Body',aliases:['DOTATATE PET','NET PET','Ga-68 PET'],cptCode:'78816',contrast:'None',contrastOptions:[],estimatedDuration:'90 min',patientPrep:['NPO 4 hours','Hydrate well'],contraindications:['Pregnancy'],commonIndications:['Neuroendocrine tumor','Carcinoid','Pheochromocytoma','Paraganglioma'],radiationDose:'Low (5 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Gallium-68 DOTATATE; 60 min uptake'},
{name:'PET/CT PSMA',modality:'PET/CT',bodyRegion:'Whole Body',aliases:['PSMA PET','Ga-68 PSMA PET','Pylarify'],cptCode:'78816',contrast:'None',contrastOptions:[],estimatedDuration:'90 min',patientPrep:['Hydrate well'],contraindications:['Pregnancy'],commonIndications:['Prostate cancer staging','Biochemical recurrence','Metastatic prostate cancer'],radiationDose:'Low (5 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Ga-68 PSMA-11 or F-18 piflufolastat; 60 min uptake'},

// ── Mammography ──
{name:'Screening Mammogram (2D)',modality:'Mammography',bodyRegion:'Breast',aliases:['Mammogram','Annual Mammogram'],cptCode:'77067',contrast:'None',contrastOptions:[],estimatedDuration:'15 min',patientPrep:['No deodorant/powder on breast/axilla day of exam'],contraindications:['Pregnancy','Breast implants (inform tech)'],commonIndications:['Annual breast cancer screening (age 40+)'],radiationDose:'Low (0.4 mSv)',sedationRequired:false,laterality:'Bilateral',lateralityOptions:['Bilateral'],specialInstructions:'CC and MLO views bilaterally; BI-RADS reporting'},
{name:'3D Mammogram (Tomosynthesis)',modality:'Mammography',bodyRegion:'Breast',aliases:['Tomo','Digital Breast Tomosynthesis','DBT'],cptCode:'77063',contrast:'None',contrastOptions:[],estimatedDuration:'15 min',patientPrep:['No deodorant/powder'],contraindications:['Pregnancy'],commonIndications:['Breast cancer screening','Dense breasts','Improved cancer detection'],radiationDose:'Low (0.5 mSv)',sedationRequired:false,laterality:'Bilateral',lateralityOptions:['Bilateral'],specialInstructions:'Reduces callbacks; better for dense breast tissue'},
{name:'Diagnostic Mammogram',modality:'Mammography',bodyRegion:'Breast',aliases:['Dx Mammogram','Diagnostic Mammo'],cptCode:'77066',contrast:'None',contrastOptions:[],estimatedDuration:'30 min',patientPrep:['No deodorant/powder'],contraindications:['Pregnancy'],commonIndications:['Palpable mass','Abnormal screening mammogram','Nipple discharge','Breast pain','Prior breast cancer'],radiationDose:'Low (0.5 mSv)',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'Includes spot compression and magnification views as needed'},
{name:'Stereotactic Breast Biopsy',modality:'Mammography',bodyRegion:'Breast',aliases:['Stereo Biopsy','Mammographic-Guided Biopsy'],cptCode:'19081',contrast:'None',contrastOptions:[],estimatedDuration:'60 min',patientPrep:['Hold anticoagulants per ordering provider','No aspirin 7 days'],contraindications:['Anticoagulation','Lesion not accessible'],commonIndications:['Suspicious calcifications','Mammographic abnormality not visible on US'],radiationDose:'Low',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right'],specialInstructions:'Prone or upright table; local anesthesia; clip placement'},

// ── DEXA ──
{name:'DEXA Bone Density (Central)',modality:'DEXA',bodyRegion:'Spine/Hip',aliases:['Bone Density','DEXA Scan','DXA','Bone Densitometry'],cptCode:'77080',contrast:'None',contrastOptions:[],estimatedDuration:'15 min',patientPrep:['No calcium supplements 24 hours before','Remove belt/metal'],contraindications:['Recent barium study','Recent nuclear medicine study'],commonIndications:['Osteoporosis screening (women 65+, men 70+)','Postmenopausal','Steroid use','Fragility fracture','Monitoring treatment'],radiationDose:'Minimal (0.001 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'L1-L4 spine and bilateral hips; T-score reporting'},
{name:'DEXA Body Composition',modality:'DEXA',bodyRegion:'Whole Body',aliases:['Body Comp DEXA','DXA Body Composition'],cptCode:'76499',contrast:'None',contrastOptions:[],estimatedDuration:'15 min',patientPrep:[],contraindications:[],commonIndications:['Body composition analysis','Sarcopenia evaluation','Research'],radiationDose:'Minimal',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Measures lean mass, fat mass, bone mineral content'},

// ── Fluoroscopy ──
{name:'Upper GI Series',modality:'Fluoroscopy',bodyRegion:'Esophagus/Stomach',aliases:['Barium Swallow','UGI Series','UGI'],cptCode:'74246',contrast:'Barium',contrastOptions:['Barium','Water-Soluble (Gastrografin)'],estimatedDuration:'30 min',patientPrep:['NPO after midnight'],contraindications:['Complete bowel obstruction (if barium)','Suspected perforation (use water-soluble)'],commonIndications:['Dysphagia','GERD','Hiatal hernia','Peptic ulcer','Post-surgical evaluation'],radiationDose:'Moderate (6 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Patient drinks barium; multiple positions; real-time imaging'},
{name:'Modified Barium Swallow',modality:'Fluoroscopy',bodyRegion:'Oropharynx',aliases:['MBS','Swallowing Study','Videofluoroscopic Swallow Study','VFSS'],cptCode:'74230',contrast:'Barium',contrastOptions:[],estimatedDuration:'30 min',patientPrep:['NPO 2 hours'],contraindications:[],commonIndications:['Dysphagia','Aspiration risk','Stroke','Head/neck cancer','Neurological disease'],radiationDose:'Low (1 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Performed with speech-language pathologist; multiple consistencies tested'},
{name:'Barium Enema',modality:'Fluoroscopy',bodyRegion:'Colon',aliases:['BE','Lower GI Series'],cptCode:'74280',contrast:'Barium',contrastOptions:['Barium','Water-Soluble'],estimatedDuration:'45 min',patientPrep:['Bowel prep (clear liquids + laxative day before)','NPO after midnight'],contraindications:['Suspected perforation','Toxic megacolon','Recent biopsy'],commonIndications:['Colorectal evaluation','Stricture','Volvulus','Post-surgical anastomosis'],radiationDose:'Moderate (8 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Air-contrast (double-contrast) technique preferred'},
{name:'VCUG',modality:'Fluoroscopy',bodyRegion:'Bladder',aliases:['Voiding Cystourethrogram','VCUG'],cptCode:'74455',contrast:'Water-Soluble',contrastOptions:[],estimatedDuration:'30 min',patientPrep:['Catheterization required'],contraindications:['Active UTI (relative)'],commonIndications:['Vesicoureteral reflux (pediatric)','Recurrent UTI','Post-surgical evaluation','Urethral stricture'],radiationDose:'Low (1-2 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Bladder catheterized and filled with contrast; images during voiding'},
{name:'HSG',modality:'Fluoroscopy',bodyRegion:'Uterus/Fallopian Tubes',aliases:['Hysterosalpingogram','HSG'],cptCode:'74740',contrast:'Water-Soluble',contrastOptions:[],estimatedDuration:'30 min',patientPrep:['Schedule day 6-12 of cycle','Pregnancy test','NSAIDs 1 hour before','Antibiotic prophylaxis if hydrosalpinx'],contraindications:['Pregnancy','Active PID','Iodine allergy'],commonIndications:['Infertility workup','Tubal patency evaluation','Uterine cavity evaluation'],radiationDose:'Low (1 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Contrast injected through cervical cannula; assess tubal fill and spillage'},
{name:'Myelogram',modality:'Fluoroscopy',bodyRegion:'Spine',aliases:['CT Myelogram'],cptCode:'72265',contrast:'Intrathecal Contrast',contrastOptions:[],estimatedDuration:'60 min',patientPrep:['Hold anticoagulants','Consent required','Check for contrast allergy'],contraindications:['Anticoagulation','Raised ICP','Spinal infection'],commonIndications:['Spinal stenosis (MRI contraindicated)','Post-surgical spine','Metallic hardware artifact on MRI','CSF leak'],radiationDose:'Moderate (4 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'LP with intrathecal contrast followed by CT; bedrest 4-24h after'},

// ── Interventional Radiology ──
{name:'CT-Guided Biopsy',modality:'Interventional',bodyRegion:'Various',aliases:['CT Biopsy','Percutaneous Biopsy'],cptCode:'77012',contrast:'None',contrastOptions:[],estimatedDuration:'60 min',patientPrep:['Check coagulation labs','Hold anticoagulants','NPO 6 hours','Consent required','IV access'],contraindications:['Uncorrectable coagulopathy','Inaccessible lesion'],commonIndications:['Lung nodule biopsy','Liver biopsy','Bone biopsy','Lymph node biopsy','Renal mass biopsy'],radiationDose:'Moderate (variable)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Local anesthesia with moderate sedation if needed; post-procedure monitoring for complications'},
{name:'US-Guided Biopsy',modality:'Interventional',bodyRegion:'Various',aliases:['Ultrasound-Guided Biopsy'],cptCode:'76942',contrast:'None',contrastOptions:[],estimatedDuration:'30-45 min',patientPrep:['Check coagulation labs','Hold anticoagulants','Consent required'],contraindications:['Uncorrectable coagulopathy'],commonIndications:['Thyroid nodule biopsy (FNA)','Liver biopsy','Kidney biopsy','Breast biopsy','Lymph node biopsy'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Real-time ultrasound guidance; local anesthesia'},
{name:'Paracentesis (US-Guided)',modality:'Interventional',bodyRegion:'Abdomen',aliases:['Abdominal Paracentesis','Abdominal Tap'],cptCode:'49083',contrast:'None',contrastOptions:[],estimatedDuration:'30 min',patientPrep:['Check coagulation labs','Consent required','Empty bladder'],contraindications:['Severe DIC','Surgical abdomen'],commonIndications:['Ascites drainage','Diagnostic (SBP evaluation)','Therapeutic (tense ascites)'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'US-guided; LLQ preferred site; send fluid for cell count, albumin, culture'},
{name:'Thoracentesis (US-Guided)',modality:'Interventional',bodyRegion:'Chest',aliases:['Pleural Tap','Chest Tap'],cptCode:'32555',contrast:'None',contrastOptions:[],estimatedDuration:'30 min',patientPrep:['Check coagulation labs','Consent required','CXR or US to confirm effusion'],contraindications:['Small effusion','Uncorrectable coagulopathy'],commonIndications:['Pleural effusion (diagnostic or therapeutic)','Empyema drainage','Dyspnea from large effusion'],radiationDose:'None',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right'],specialInstructions:'US-guided; max 1500 mL per session; send fluid for cell count, LDH, protein, culture, cytology'},
{name:'PICC Line Placement',modality:'Interventional',bodyRegion:'Upper Extremity',aliases:['PICC','PICC Insertion','Peripherally Inserted Central Catheter'],cptCode:'36569',contrast:'None',contrastOptions:[],estimatedDuration:'30-60 min',patientPrep:['Consent required','Coagulation labs','Arm selection (avoid side of fistula/mastectomy)'],contraindications:['Bilateral upper extremity DVT','Skin infection at insertion site'],commonIndications:['Prolonged IV access','IV antibiotics >7 days','TPN','Chemotherapy','Difficult peripheral access'],radiationDose:'None',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right'],specialInstructions:'US-guided insertion; confirm tip position with CXR'},
{name:'Port Placement',modality:'Interventional',bodyRegion:'Chest',aliases:['Port-a-Cath','Mediport','Implantable Port'],cptCode:'36561',contrast:'None',contrastOptions:[],estimatedDuration:'60 min',patientPrep:['NPO 6 hours','Consent required','Coagulation labs','IV access'],contraindications:['Skin infection at site','SVC thrombosis'],commonIndications:['Chemotherapy','Frequent blood draws','Long-term IV access','TPN'],radiationDose:'Minimal (fluoroscopy)',sedationRequired:true,laterality:'Left',lateralityOptions:['Left','Right'],specialInstructions:'Subcutaneous port with central venous catheter; moderate sedation; confirm with CXR'},
{name:'IVC Filter Placement',modality:'Interventional',bodyRegion:'Abdomen',aliases:['IVC Filter','Inferior Vena Cava Filter'],cptCode:'37191',contrast:'With Contrast',contrastOptions:[],estimatedDuration:'60 min',patientPrep:['Consent required','Coagulation labs','IV access'],contraindications:['IVC thrombosis (complete)','Uncorrectable coagulopathy'],commonIndications:['DVT/PE with contraindication to anticoagulation','Recurrent PE despite anticoagulation','Prophylactic (major trauma/surgery)'],radiationDose:'Moderate',sedationRequired:true,laterality:'N/A',lateralityOptions:[],specialInstructions:'Retrievable filters preferred; plan for retrieval when anticoagulation is possible'},
{name:'Joint Injection (Fluoroscopy-Guided)',modality:'Interventional',bodyRegion:'Joint',aliases:['Fluoroscopic Joint Injection','Therapeutic Joint Injection'],cptCode:'77002',contrast:'Fluoroscopy',contrastOptions:[],estimatedDuration:'30 min',patientPrep:['Consent required'],contraindications:['Joint infection','Overlying skin infection'],commonIndications:['Osteoarthritis','Joint pain','Synovitis','Therapeutic steroid injection','Aspiration'],radiationDose:'Low',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right'],specialInstructions:'Fluoroscopy confirms needle position; steroid +/- local anesthetic'},

// ── Echocardiography ──
{name:'Transthoracic Echocardiogram',modality:'Ultrasound',bodyRegion:'Heart',aliases:['TTE','Echo','Echocardiogram','Cardiac Echo'],cptCode:'93306',contrast:'None',contrastOptions:['None','With Contrast (Definity)'],estimatedDuration:'45-60 min',patientPrep:[],contraindications:[],commonIndications:['Heart failure','Valvular disease','Chest pain','Dyspnea','Murmur evaluation','Pre-operative cardiac assessment','Cardiomyopathy'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Left lateral decubitus position; includes 2D, M-mode, Doppler, and color flow'},
{name:'Transesophageal Echocardiogram',modality:'Ultrasound',bodyRegion:'Heart',aliases:['TEE'],cptCode:'93312',contrast:'None',contrastOptions:[],estimatedDuration:'60-90 min',patientPrep:['NPO 6 hours','IV access','Consent required','Anesthesia consultation if needed'],contraindications:['Esophageal stricture','Esophageal perforation','Active GI bleeding','Cervical spine instability'],commonIndications:['Endocarditis','Atrial fibrillation (LAA thrombus)','Prosthetic valve evaluation','Aortic dissection','Intraoperative monitoring','PFO/ASD evaluation'],radiationDose:'None',sedationRequired:true,laterality:'N/A',lateralityOptions:[],specialInstructions:'Moderate sedation required; antibiotic prophylaxis if indicated'},
{name:'Stress Echocardiogram',modality:'Ultrasound',bodyRegion:'Heart',aliases:['Stress Echo','Exercise Echo','Dobutamine Stress Echo'],cptCode:'93351',contrast:'None',contrastOptions:['None','With Contrast (Definity)'],estimatedDuration:'60-90 min',patientPrep:['No caffeine 24 hours','No beta-blockers day of test (if exercise)','NPO 4 hours'],contraindications:['Acute MI','Unstable angina','Severe aortic stenosis','Decompensated heart failure'],commonIndications:['Coronary artery disease evaluation','Chest pain','Pre-operative risk stratification','Valvular assessment with exercise'],radiationDose:'None',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Exercise preferred; dobutamine protocol if unable to exercise'},

// ── Doppler Vascular ──
{name:'Venous Doppler Lower Extremity',modality:'Ultrasound',bodyRegion:'Lower Extremity',aliases:['DVT Study','Lower Extremity Duplex','Venous Duplex LE','DVT Ultrasound'],cptCode:'93971',contrast:'None',contrastOptions:[],estimatedDuration:'30-45 min',patientPrep:[],contraindications:[],commonIndications:['DVT evaluation','Leg swelling','Post-thrombotic syndrome','Pre-operative DVT screening','Calf pain'],radiationDose:'None',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'Compression and Doppler assessment of common femoral through popliteal veins'},
{name:'Venous Doppler Upper Extremity',modality:'Ultrasound',bodyRegion:'Upper Extremity',aliases:['Upper Extremity Duplex','Venous Duplex UE'],cptCode:'93971',contrast:'None',contrastOptions:[],estimatedDuration:'30-45 min',patientPrep:[],contraindications:[],commonIndications:['Upper extremity DVT','PICC/port-associated thrombosis','Arm swelling','SVC syndrome evaluation'],radiationDose:'None',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'Includes subclavian, axillary, brachial, basilic, and cephalic veins'},
{name:'Carotid Duplex Ultrasound',modality:'Ultrasound',bodyRegion:'Neck',aliases:['Carotid Doppler','Carotid Ultrasound','Carotid Duplex'],cptCode:'93880',contrast:'None',contrastOptions:[],estimatedDuration:'30-45 min',patientPrep:[],contraindications:[],commonIndications:['Stroke/TIA evaluation','Carotid bruit','Pre-operative assessment','Carotid stenosis follow-up','Asymptomatic screening in high-risk patients'],radiationDose:'None',sedationRequired:false,laterality:'Bilateral',lateralityOptions:['Bilateral'],specialInstructions:'B-mode imaging with spectral and color Doppler; NASCET criteria for stenosis grading'},
{name:'Arterial Doppler Lower Extremity',modality:'Ultrasound',bodyRegion:'Lower Extremity',aliases:['ABI','Arterial Duplex LE','Lower Extremity Arterial'],cptCode:'93926',contrast:'None',contrastOptions:[],estimatedDuration:'45-60 min',patientPrep:[],contraindications:[],commonIndications:['Peripheral arterial disease','Claudication','Non-healing wound','ABI assessment','Post-bypass graft surveillance'],radiationDose:'None',sedationRequired:false,laterality:'Left',lateralityOptions:['Left','Right','Bilateral'],specialInstructions:'Includes ankle-brachial index and segmental pressures'},

// ── Nuclear Medicine — Missing Studies ──
{name:'V/Q Scan',modality:'Nuclear Medicine',bodyRegion:'Chest',aliases:['Ventilation-Perfusion Scan','VQ Scan','Lung Scan'],cptCode:'78582',contrast:'None',contrastOptions:[],estimatedDuration:'60-90 min',patientPrep:['Recent CXR required'],contraindications:['Severe pulmonary hypertension (relative)'],commonIndications:['Pulmonary embolism (alternative to CTPA)','Contrast allergy (cannot do CTPA)','Renal insufficiency','Pregnancy (lower radiation than CTPA)'],radiationDose:'Low (2 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Ventilation phase (inhaled Xe-133 or Tc-99m DTPA aerosol) followed by perfusion phase (IV Tc-99m MAA); interpreted as normal/low/intermediate/high probability'},
{name:'Bone Scan',modality:'Nuclear Medicine',bodyRegion:'Whole Body',aliases:['Bone Scintigraphy','Skeletal Scintigraphy','Tc-99m MDP Scan'],cptCode:'78300',contrast:'None',contrastOptions:[],estimatedDuration:'3-4 hours (delayed imaging)',patientPrep:['Good hydration','Void frequently after injection'],contraindications:['Pregnancy','Breastfeeding (pump and dump 24h)'],commonIndications:['Bone metastases','Stress fracture','Osteomyelitis','Paget disease','Prosthetic loosening','Reflex sympathetic dystrophy'],radiationDose:'Moderate (6 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'Injection then 2-4 hour delay before imaging; three-phase for infection/RSD'},

// ── DEXA ──
{name:'DEXA Scan',modality:'DEXA',bodyRegion:'Hip/Spine',aliases:['Bone Density','DXA','Bone Densitometry','Osteoporosis Screening'],cptCode:'77080',contrast:'None',contrastOptions:[],estimatedDuration:'15-20 min',patientPrep:['No calcium supplements day of test'],contraindications:['Recent barium/contrast (wait 7 days)','Pregnancy'],commonIndications:['Osteoporosis screening','Osteoporosis monitoring','Fracture risk assessment','Steroid-induced osteoporosis','Post-menopausal women age 65+','Men age 70+'],radiationDose:'Minimal (0.001 mSv)',sedationRequired:false,laterality:'N/A',lateralityOptions:[],specialInstructions:'T-score interpretation: >-1.0 normal, -1.0 to -2.5 osteopenia, <-2.5 osteoporosis; FRAX calculation recommended'},
];

/* ============================================================
   Imaging Search & Autocomplete Functions
   ============================================================ */

function searchImagingStudies(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  const scored = [];
  for (const img of IMAGING_DB) {
    const nLower = img.name.toLowerCase();
    const aliasLower = img.aliases.map(a => a.toLowerCase());
    const modLower = img.modality.toLowerCase();
    const regLower = img.bodyRegion.toLowerCase();
    let score = 0;
    if (nLower.startsWith(q)) score = 4;
    else if (aliasLower.some(a => a.startsWith(q))) score = 3;
    else if (nLower.includes(q)) score = 2;
    else if (aliasLower.some(a => a.includes(q))) score = 2;
    else if (modLower.includes(q)) score = 1;
    else if (regLower.includes(q)) score = 1;
    if (score > 0) scored.push({ img, score });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, 10).map(s => s.img);
}

function searchImagingByModality(modality) {
  return IMAGING_DB.filter(i => i.modality === modality);
}

function getImagingByBodyRegion(region) {
  const q = region.toLowerCase();
  return IMAGING_DB.filter(i => i.bodyRegion.toLowerCase().includes(q));
}

function getImagingModalities() {
  const mods = [];
  for (const img of IMAGING_DB) {
    if (mods.indexOf(img.modality) < 0) mods.push(img.modality);
  }
  return mods;
}

function getImagingBodyRegions() {
  const regions = [];
  for (const img of IMAGING_DB) {
    if (regions.indexOf(img.bodyRegion) < 0) regions.push(img.bodyRegion);
  }
  return regions.sort();
}

function attachImagingAutocomplete(inputEl, opts) {
  const onSelect = opts.onSelect || (() => {});
  const dropdown = document.createElement('div');
  dropdown.className = 'med-autocomplete-dropdown';
  dropdown.hidden = true;
  let container = inputEl.parentElement;
  if (!container.classList.contains('med-autocomplete-container')) {
    container = document.createElement('div');
    container.className = 'med-autocomplete-container';
    inputEl.parentNode.insertBefore(container, inputEl);
    container.appendChild(inputEl);
  }
  container.appendChild(dropdown);
  let highlighted = -1;
  let currentResults = [];
  let debounceTimer = null;

  function renderDropdown(results) {
    currentResults = results;
    highlighted = -1;
    dropdown.innerHTML = '';
    if (results.length === 0) { dropdown.hidden = true; return; }
    results.forEach((img, i) => {
      const item = document.createElement('div');
      item.className = 'med-autocomplete-item';
      item.dataset.index = i;
      item.innerHTML =
        '<span class="med-autocomplete-drug">' + esc(img.name) + '</span>' +
        ' <span class="med-autocomplete-class">' + esc(img.modality) + '</span>' +
        '<span class="med-autocomplete-brand"> · ' + esc(img.bodyRegion) + '</span>';
      item.addEventListener('mousedown', e => { e.preventDefault(); selectItem(i); });
      item.addEventListener('mouseenter', () => { setHighlight(i); });
      dropdown.appendChild(item);
    });
    dropdown.hidden = false;
  }

  function setHighlight(idx) {
    const items = dropdown.querySelectorAll('.med-autocomplete-item');
    items.forEach((el, i) => { el.classList.toggle('highlighted', i === idx); });
    highlighted = idx;
    if (items[idx]) items[idx].scrollIntoView({ block: 'nearest' });
  }

  function selectItem(idx) {
    const img = currentResults[idx];
    if (!img) return;
    inputEl.value = img.name;
    dropdown.hidden = true;
    currentResults = [];
    onSelect(img);
  }

  inputEl.addEventListener('input', () => {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      const q = inputEl.value.trim();
      if (q.length < 2) { dropdown.hidden = true; currentResults = []; return; }
      renderDropdown(searchImagingStudies(q));
    }, 150);
  });

  inputEl.addEventListener('keydown', e => {
    if (dropdown.hidden || currentResults.length === 0) return;
    if (e.key === 'ArrowDown') { e.preventDefault(); setHighlight(Math.min(highlighted + 1, currentResults.length - 1)); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); setHighlight(Math.max(highlighted - 1, 0)); }
    else if (e.key === 'Enter') { if (highlighted >= 0) { e.preventDefault(); selectItem(highlighted); } }
    else if (e.key === 'Escape') { dropdown.hidden = true; currentResults = []; }
  });

  inputEl.addEventListener('blur', () => { setTimeout(() => { dropdown.hidden = true; }, 200); });
  inputEl.addEventListener('focus', () => {
    const q = inputEl.value.trim();
    if (q.length >= 2 && currentResults.length > 0) dropdown.hidden = false;
  });

  return { dropdown, destroy: () => { clearTimeout(debounceTimer); dropdown.remove(); } };
}
